apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-vertx-service
spec:
  selector:
    matchLabels:
      app: account-vertx-service
  template:
    metadata:
      labels:
        app: account-vertx-service
    spec:
      containers:
      - name: account-vertx-service
        image: account-vertx-service
        ports:
        - containerPort: 8080
