apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: sample-vertx-kubernetes
build:
  artifacts:
    - image: account-vertx-service
      docker:
        dockerfile: account-vertx-service/Dockerfile
    - image: customer-vertx-service
      docker:
        dockerfile: customer-vertx-service/Dockerfile
  tagPolicy:
    gitCommit: {}
manifests:
  rawYaml:
    - 'k8s/*.yaml'
    - '*/k8s/*.yaml'
deploy:
  kubectl: {}